name: CI Titanius

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Ejecutar pruebas (Validación de sintaxis PHP)
        run: php -l error2.php" -exec php -l {} \;

      - name: Generar artefacto del proyecto (Actividad 5)
        uses: actions/upload-artifact@v4
        with:
          name: titanius-app-compilado
          path: .
